-- DROP TABLE `ac_unit_history`;
-- --> statement-breakpoint
-- CREATE TABLE `ac_unit_history` (
-- 	`id` text PRIMARY KEY NOT NULL,
-- 	`ac_unit_id` text NOT NULL,
-- 	`user_id` text,
-- 	`changes` text NOT NULL,
-- 	`note` text,
-- 	`photos` text,
-- 	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
-- 	FOREIGN KEY (`ac_unit_id`) REFERENCES `ac_units`(`id`) ON UPDATE no action ON DELETE cascade,
-- 	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
-- );
